.TH ALSAUNMUTE 1 "13 January 2016"
.SH NAME
alsaunmute \- a command to (re)initialize sound hardware

.SH SYNOPSIS
\fBalsaunmute\fP

.SH DESCRIPTION
\fBalsaunmute\fP is a command\-line utility which initializes
all mixer volume controls to initial values.

.SH OPTIONS
No options available.

.SH SEE ALSO
\fB
amixer(1)
alsamixer(1)
alsactl(1)
