.TH ALSA-DELAY 1 "13 January 2016"
.SH NAME
alsadelay \- a command to (re)initialize sound hardware

.SH SYNOPSIS
\fBalsa-delay\fP \fI[options]\fP \fIrequested_delay_in_ms\fP [\fIoutput_card\fP[,\fIdevice\fP]]

.SH DESCRIPTION
\fBalsa-delay\fP is a command\-line utility to setup an audio
delay. The snd-aloop ALSA driver is used to send all PCM streams
back to the user space and the alsaloop utility is used to send
this stream to a real hardware.

The parameter \fIoutput_card\fP is ALSA card index (number) or
string card identifier. The parameter \fIdevice\fP is ALSA device number.

Use \fIaplay -l\fP to list available cards and devices.


.SH OPTIONS
.TP
\fI\-\-h,\-\-help\fP
Print help.
.TP
\fI\-\-q,\-\-quiet\fP
Quiet mode.
.TP
\fI\-\-y,\-\-yes\fP
Do not ask any questions - answer is always yes.
.TP
\fI\-\-c,\-\-clean\fP
Clean temporary directory.
.TP
\fI\-\-r,\-\-revert\fP
Revert configuration changes (modprobe, pulse-audio).
.TP
\fI\-\-tmpdir=<DIR>\fP
Set temporary directory.

.SH OPTIONS (for alsaloop daemon)
.TP
\fI\-\-pdevice=<DEV>\fP
Force playback device.
.TP
\fI\-\-cdevice=<DEV>\fP
Force capture device.
.TP
\fI\-\-pctl=<DEV>\fP
Force playback control device.
.TP
\fI\-\-cctl=<DEV>\fP
Force capture control device.
.TP
\fI\-\-one=<ARG>\fP
Pass this argument to last thread.
.TP
\fI\-\-arg=<ARG>\fP
Pass this argument to all threads.
.TP
\fI\-\-mix=<ARG>\fP
Redirect ALSA mixer controls to OSS mixer (default is Master).
.TP
\fI\-\-pa\fP
Redirect pulse-audio to alsaloop.

.SH NOTE

For devices, the string %s is replaced with the card index
and second string %s is replaced with the device index
and third string %s is replaced the substream index (0-7).

Example: hw:%s,%s,%s (card, device, substream)

.SH SEE ALSO
\fB
alsaloop(1)
amixer(1)
alsamixer(1)
